# Generated by Django 4.2.1 on 2023-06-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_time',
        ),
    ]
