# Generated by Django 4.2.2 on 2025-05-08 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=1000)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='ModelMessage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.CharField(max_length=1000)),
                ('content', models.JSONField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='agent.usermessage')),
            ],
            options={
                'db_table': 'model_message',
            },
        ),
    ]
