# Generated by Django 4.2.2 on 2025-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmessage',
            name='ai_model',
        ),
        migrations.AddField(
            model_name='modelmessage',
            name='model_used',
            field=models.CharField(default='', help_text='AI model used for this message', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='model_used',
            field=models.CharField(default='gemini', help_text='AI model used for this message', max_length=1000),
            preserve_default=False,
        ),
    ]
