import React from 'react'

const Footer = () => {
    return (
        <>
            <div className="max-w-7xl mx-auto px-4 grid grid-cols-1 md:grid-cols-4 gap-8 pt-20">
                {/* About Section */}
                <div>
                    <h3 className="text-lg font-semibold mb-3 underline">
                        About
                    </h3>
                    <ul className="space-y-2">
                        <li>
                            <a href="#" className="hover:underline">
                                About the AI
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                How It Works
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                Why AI Blogs?
                            </a>
                        </li>
                    </ul>
                </div>

                {/* Quick Links */}
                <div>
                    <h3 className="text-lg font-semibold mb-3 underline">
                        Quick Links
                    </h3>
                    <ul className="space-y-2">
                        <li>
                            <a href="#" className="hover:underline">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                Browse Blogs
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                Categories
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                Contact
                            </a>
                        </li>
                    </ul>
                </div>

                {/* Legal */}
                <div>
                    <h3 className="text-lg font-semibold mb-3 underline">
                        Legal
                    </h3>
                    <ul className="space-y-2">
                        <li>
                            <a href="#" className="hover:underline">
                                Privacy Policy
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                Terms of Service
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                Content Disclaimer
                            </a>
                        </li>
                    </ul>
                </div>

                {/* Connect */}
                <div>
                    <h3 className="text-lg font-semibold mb-3 underline">
                        Connect
                    </h3>
                    <ul className="space-y-2">
                        <li>
                            <a href="#" className="hover:underline">
                                Subscribe to Newsletter
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                Follow on Twitter
                            </a>
                        </li>
                        <li>
                            <a href="#" className="hover:underline">
                                GitHub
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            {/* Bottom Note */}
            <div className="mt-10 text-center border-t border-primary pt-6 text-sm text-gray-400">
                <p>© 2025 AIBlogX. All content generated by AI.</p>
                <p className="mt-2">
                    Written with ❤️ by an AI. Verify information when needed.
                </p>
            </div>
        </>
    );
};

export default Footer;
