# Generated by Django 4.2.2 on 2025-05-09 07:16

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='blogurl',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default='asdaasda', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogurl',
            name='is_feed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='admin_panal.tags'),
        ),
    ]
