# Generated by Django 4.2.2 on 2025-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panal', '0002_tags_remove_blogpost_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
