# Generated by Django 4.2.1 on 2023-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panal', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUrls',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
