# Generated by Django 4.2.1 on 2023-06-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panal', '0003_blogurls_delete_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogUrls',
            new_name='BlogUrl',
        ),
    ]
