# Generated by Django 4.2.2 on 2025-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panal', '0004_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_id',
            field=models.CharField(db_index=True, default='kjkjk', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
