# Generated by Django 4.2.1 on 2023-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panal', '0004_rename_blogurls_blogurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=10000)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
